global using EOMWeb.BusinessServices;
global using EOMWeb.DbServices;
global using EOMWeb.Shared;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Threading.Tasks;
